# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
      displayName: 'Get latest Github Changes to all branches'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script:
      git push https://GeneralMills@dev.azure.com/GeneralMills/BoxTops/_git/BoxTopsAPISpec -u --all
      displayName:'Push lates Github Changes to Master'
